version: '3.9'
services:
  app:
    build: .
    container_name: mas_app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    networks:
      - mas-network

  db:
    image: postgres:15-alpine
    container_name: mas_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - mas-network

volumes:
  pgdata:

networks:
  mas-network:
    driver: bridge