version: "3.9"
services:
  app:
    build: .
    env_file: .env
    environment:
      DB_HOST: db         # <-- здесь явно говорим, что база лежит на сервисе db
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d   # ← монтируем init скрипты

volumes:
  pgdata:
