# monitoring/prometheus.yml
global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'ecommerce-mas-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']